### ISSUE TITLE
Process exits while receiving request

### ISSUE THREAD

**Issue by qnxdev** [pacslab/ChainFaaS#14]
When a new request is received the process get and error and exits

`You logged in to RabbitMQ!
 [x] Awaiting RPC requests
b'{"task": "ghaemisr/node-info", "task_developer": 16, "job": 833}'
Received a request, running docker file.
https://chainfaas.com/provider/job_ack?job=833
Before run docker
Pull done!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.40/containers/create?name=provider_container_1`

**Comment by ghaemisr** [comment]
I just ran a provider to make sure everything is working fine and did not run into any issues. This is probably an issue with the environment that you are running the provider on. First, try running the "ghaemisr/node-info" docker on your machine separate from the provider code and make sure it runs properly. If that was not the problem, provide more details about your development environment such as the OS, the version of docker that you are using, etc. Also, if you could provide the steps to reproduce the error that would also be helpful.
